	TARGET = web_radio


IDF_PATH =/home/allen/esp/esp-who/esp-idf

	INCLUDEPATH += \
			$${IDF_PATH}/components/app_trace/sys_view/Config \
			$${IDF_PATH}/components/app_trace/sys_view/SEGGER \
			$${IDF_PATH}/components/app_trace/sys_view/Sample/OS \
			$${IDF_PATH}/components/bt/bluedroid/btc/include \
			$${IDF_PATH}/components/bt/bluedroid/common/include \
			$${IDF_PATH}/components/bt/bluedroid/external/sbc/decoder/include \
			$${IDF_PATH}/components/bt/bluedroid/osi/include \
			$${IDF_PATH}/components/bt/bluedroid/stack/include \
			$${IDF_PATH}/components/driver/include \
			$${IDF_PATH}/components/esp32/include \
			$${IDF_PATH}/components/esp_event/include \
			$${IDF_PATH}/components/esp_ringbuf/include \
			$${IDF_PATH}/components/ethernet/include \
			$${IDF_PATH}/components/fatfs/src \
			$${IDF_PATH}/components/freertos/include \
			$${IDF_PATH}/components/freertos/include/freertos \
			$${IDF_PATH}/components/heap/include \
			$${IDF_PATH}/components/json/cJSON \
			$${IDF_PATH}/components/lwip/include/apps \
			$${IDF_PATH}/components/lwip/lwip/src/include \
			$${IDF_PATH}/components/lwip/lwip/src/include/lwip \
			$${IDF_PATH}/components/lwip/port/esp32/include \
			$${IDF_PATH}/components/newlib/include \
			$${IDF_PATH}/components/newlib/include/sys \
			$${IDF_PATH}/components/newlib/platform_include \
			$${IDF_PATH}/components/newlib/platform_include/sys \
			$${IDF_PATH}/components/nghttp/nghttp2/lib/includes \
			$${IDF_PATH}/components/nghttp/nghttp2/src \
			$${IDF_PATH}/components/nghttp/port/include \
			$${IDF_PATH}/components/nvs_flash/include \
			$${IDF_PATH}/components/soc/esp32/include \
			$${IDF_PATH}/components/soc/esp32/include/soc \
			$${IDF_PATH}/components/soc/include \
			$${IDF_PATH}/components/spi_flash/include \
			$${IDF_PATH}/components/spi_flash/sim/stubs/driver/include \
			$${IDF_PATH}/components/spi_flash/sim/stubs/driver/include/driver \
			$${IDF_PATH}/components/spi_flash/sim/stubs/esp32/include \
			$${IDF_PATH}/components/spi_flash/sim/stubs/freertos/include \
			$${IDF_PATH}/components/spi_flash/sim/stubs/freertos/include/freertos \
			$${IDF_PATH}/components/spi_flash/sim/stubs/log/include \
			$${IDF_PATH}/components/spi_flash/sim/stubs/sdmmc/include \
			$${IDF_PATH}/components/tcpip_adapter/include \
			$${IDF_PATH}/components/vfs/include \
			$${IDF_PATH}/components/vfs/include/sys \
			$${IDF_PATH}/components/wear_levelling/include 

	XTENSA_TOOLCHAIN += $$(HOME)/esp/xtensa-esp32-elf
	INCLUDEPATH += \
			$${XTENSA_TOOLCHAIN}/xtensa-esp32-elf/include \
			$${XTENSA_TOOLCHAIN}/xtensa-esp32-elf/include/c++/5.2.0 \
			$${XTENSA_TOOLCHAIN}/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf \
			$${XTENSA_TOOLCHAIN}/lib/gcc/xtensa-esp32-elf/5.2.0/include \
			$${XTENSA_TOOLCHAIN}/lib/gcc/xtensa-esp32-elf/5.2.0/include-fixed \
			$${XTENSA_TOOLCHAIN}/lib/gcc/xtensa-esp32-elf/include/sys 

	INCLUDEPATH += \
			../../components/audio/include \
			../../components/bsp/include \
			../../components/espressif/include \
			../../components/euler/include \
			../../components/fifo/include \
			../../components/hal/include \
			../../components/http/include \
			../../components/libmdns/include \
			../../components/mad/include \
			../../components/speex/libspeex \
			../../components/speex/win32 \
			../../components/webserver/include \
			build/include \
			main/include \
			../web_server/build/include/config/btdm/controller/pinned/to \
			../web_server/build/include/config/fatfs/fs \
			../web_server/build/include/config/lwip/max \
			../web_server/build/include/config/mbedtls/have \
			../web_server/build/include/config/mpu \
			../web_server/build/include/config/mqtt/transport \
			../web_server/build/include/config/spibus/log/rw/level \
			../web_server/build/include/config/wl/sector/mode 

	SOURCES += \
			build/include/config/auto.conf \
			main/main.c \
			main/mp3_decode.c \
			main/web_radio.c \
			../../components/I2Cbus/src/I2Cbus.cpp \
			../../components/MPUdriver/src/MPU.cpp \
			../../components/MPUdriver/src/MPUdmp.cpp \
			../../components/SPIbus/src/SPIbus.cpp \
			../../components/liblame/library/VbrTag.c \
			../../components/mad/align.c \
			../../components/audio/aplay.c \
			../../components/MPUdriver/test/unit-test-app/main/app_main.cpp \
			../web_server/build/include/config/auto.conf \
			../web_server/build/include/config/auto.conf.cmd \
			../3d_show/node_modules/async-limiter/coverage/lcov-report/base.css \
			../../components/mad/bit.c \
			../../components/speex/libspeex/bits.c \
			../../components/liblame/library/bitstream.c \
			../../components/bt_speaker/bt_app_av.c \
			../../components/bt_speaker/bt_app_core.c \
			../../components/bt_speaker/bt_speaker.c \
			../../components/helix/src/buffers.c \
			../../components/speex/libspeex/cb_search.c \
			../../components/MPUdriver/docs/doxygen/customdoxygen.css \
			../../components/helix/src/dct32.c \
			../../components/mad/decoder.c \
			../../components/helix/src/dequant.c \
			../../components/helix/src/dqchan.c \
			../../components/liblame/library/encoder.c \
			../../components/espressif/eth.c \
			../../components/euler/euler.cpp \
			../../components/espressif/event.c \
			../../components/helix/example.c \
			../../components/speex/libspeex/exc_10_16_table.c \
			../../components/speex/libspeex/exc_10_32_table.c \
			../../components/speex/libspeex/exc_20_32_table.c \
			../../components/speex/libspeex/exc_5_256_table.c \
			../../components/speex/libspeex/exc_5_64_table.c \
			../../components/speex/libspeex/exc_8_128_table.c \
			../../components/liblame/library/fft.c \
			../../components/speex/libspeex/filters.c \
			../../components/mad/fixed.c \
			../../components/mad/frame.c \
			../../components/ftp/ftpd.c \
			../../components/liblame/library/gain_analysis.c \
			../../components/speex/libspeex/gain_table.c \
			../../components/speex/libspeex/gain_table_lbr.c \
			../../components/hal/hal_eth.c \
			../../components/hal/hal_i2c.c \
			../../components/hal/hal_i2s.c \
			../../components/hal/hal_tim.c \
			../../components/speex/libspeex/hexc_10_32_table.c \
			../../components/speex/libspeex/hexc_table.c \
			../../components/speex/libspeex/high_lsp_tables.c \
			../../components/http/http.c \
			../../components/mad/huffman.c \
			../../components/helix/src/hufftabs.c \
			../../components/liblame/library/id3tag.c \
			../../components/helix/src/imdct.c \
			../../components/euler/imuUpdate.cpp \
			../../components/speex/libspeex/kiss_fft.c \
			../../components/speex/libspeex/kiss_fftr.c \
			../../components/liblame/library/lame.c \
			../../components/mad/mpg12/layer12.c \
			../../components/mad/layer3.c \
			../../components/speex/libspeex/lpc.c \
			../../components/speex/libspeex/lsp.c \
			../../components/speex/libspeex/lsp_tables_nb.c \
			../../components/speex/libspeex/ltp.c \
			../web_server/main/main.c \
			../../components/SPIbus/examples/main/main.cpp \
			../../components/libmdns/mdns_task.c \
			../../components/speex/libspeex/modes.c \
			../../components/speex/libspeex/modes_wb.c \
			main/mp3_decode.c \
			../../components/helix/src/mp3dec.c \
			../../components/helix/src/mp3tabs.c \
			../../components/liblame/library/mpglib_interface.c \
			../../components/bsp/mpu6050.c \
			../../components/MPUdriver/examples/mpu_i2c/main/mpu_i2c.cpp \
			../../components/MPUdriver/examples/mpu_real/main/mpu_real.cpp \
			../../components/MPUdriver/examples/mpu_spi/main/mpu_spi.cpp \
			../../components/speex/libspeex/nb_celp.c \
			../../components/liblame/library/newmdct.c \
			../../components/helix/src/polyphase.c \
			../../components/liblame/library/presets.c \
			../3d_show/node_modules/async-limiter/coverage/lcov-report/prettify.css \
			../../components/liblame/library/psymodel.c \
			../../components/speex/libspeex/quant_lsp.c \
			../../components/liblame/library/quantize.c \
			../../components/liblame/library/quantize_pvt.c \
			../../components/liblame/library/reservoir.c \
			../../components/speex/libspeex/sb_celp.c \
			../../components/helix/src/scalfact.c \
			../../components/liblame/library/set_get.c \
			../../components/speex/libspeex/smallft.c \
			../../components/speex/libspeex/speex.c \
			../../components/speex/ti/speex_C54_test/speex_C54_test.cmd \
			../../components/speex/ti/speex_C55_test/speex_C55_test.cmd \
			../../components/speex/ti/speex_C64_test/speex_C64_test.cmd \
			../../components/speex/libspeex/speex_callbacks.c \
			../../components/speex/libspeex/speex_header.c \
			../../components/fifo/spiram_fifo.c \
			../../components/speex/libspeex/stereo.c \
			../../components/helix/src/stproc.c \
			../../components/mad/stream.c \
			../../components/helix/src/subband.c \
			../../components/mad/synth.c \
			../../components/mad/synth_stereo.c.unused \
			../../components/liblame/library/tables.c \
			../../components/liblame/library/takehiro.c \
			../../components/MPUdriver/test/mpu-tests/test_mpu.cpp \
			../../components/speex/ti/testenc-TI-C5x.c \
			../../components/speex/ti/testenc-TI-C64x.c \
			../../components/speex/libspeex/testenc.c \
			../../components/speex/libspeex/testenc_uwb.c \
			../../components/speex/libspeex/testenc_wb.c \
			../../components/mad/timer.c \
			../../components/helix/src/trigtabs.c \
			../web_server/build/include/config/tristate.conf \
			../../components/http/url_parser.c \
			../../components/liblame/library/util.c \
			../../components/speex/libspeex/vbr.c \
			../../components/liblame/library/vbrquantize.c \
			../../components/mad/version.c \
			../../components/speex/libspeex/vorbis_psy.c \
			../../components/speex/libspeex/vq.c \
			main/web_radio.c \
			../../components/webserver/webserver.c \
			../../components/websocket/websocket.c \
			../../components/websocket/websocket.cpp \
			../../components/espressif/wifi.c \
			../../components/speex/libspeex/window.c \
			../../components/bsp/wm8978.c \
			../../components/liblame/library/xmm_quantize_sub.c 

